# Generated by Django 4.2.7 on 2023-11-18 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='Country')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=200)),
                ('l_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccergames.country')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccergames.league')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(null=True)),
                ('last_games', models.CharField(choices=[('W', 'WIN'), ('D', 'DRAW'), ('L', 'LOSE')], max_length=5)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_odd', models.FloatField()),
                ('draw_odd', models.FloatField()),
                ('away_odd', models.FloatField()),
                ('to_win', models.IntegerField(default=1)),
                ('goals', models.CharField(max_length=1)),
                ('result', models.BooleanField(blank=True, null=True)),
                ('g_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccergames.country')),
                ('g_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccergames.league')),
            ],
        ),
    ]
