# Generated by Django 4.2.7 on 2023-11-18 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='games',
            name='home_team',
        ),
    ]
