# Generated by Django 4.2.7 on 2023-11-18 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0002_remove_games_away_team_remove_games_home_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='soccergames.team'),
        ),
        migrations.AddField(
            model_name='games',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='soccergames.team'),
        ),
    ]
