# Generated by Django 4.2.7 on 2023-11-20 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0004_remove_games_last_games_headtohead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headtohead',
            name='draw',
        ),
        migrations.RemoveField(
            model_name='headtohead',
            name='ht_team1',
        ),
        migrations.RemoveField(
            model_name='headtohead',
            name='lost',
        ),
        migrations.RemoveField(
            model_name='headtohead',
            name='win',
        ),
        migrations.AddField(
            model_name='games',
            name='headtohead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='soccergames.headtohead'),
        ),
        migrations.AddField(
            model_name='headtohead',
            name='g1',
            field=models.CharField(choices=[('W', 'Win'), ('D', 'Draw'), ('L', 'Loss')], default='W', max_length=1),
        ),
        migrations.AddField(
            model_name='headtohead',
            name='g2',
            field=models.CharField(choices=[('W', 'Win'), ('D', 'Draw'), ('L', 'Loss')], default='W', max_length=1),
        ),
        migrations.AddField(
            model_name='headtohead',
            name='g3',
            field=models.CharField(choices=[('W', 'Win'), ('D', 'Draw'), ('L', 'Loss')], default='W', max_length=1),
        ),
        migrations.AddField(
            model_name='headtohead',
            name='g4',
            field=models.CharField(choices=[('W', 'Win'), ('D', 'Draw'), ('L', 'Loss')], default='W', max_length=1),
        ),
        migrations.AddField(
            model_name='headtohead',
            name='g5',
            field=models.CharField(choices=[('W', 'Win'), ('D', 'Draw'), ('L', 'Loss')], default='W', max_length=1),
        ),
        migrations.AddField(
            model_name='headtohead',
            name='team',
            field=models.ManyToManyField(to='soccergames.team'),
        ),
    ]
