# Generated by Django 4.2.7 on 2023-11-20 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0006_remove_games_headtohead'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='headhead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soccergames.headtohead'),
        ),
    ]
