# Generated by Django 4.2.7 on 2023-11-23 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0007_games_headhead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='g_league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='soccergames.league'),
        ),
    ]
