# Generated by Django 4.2.7 on 2023-11-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0011_rename_games_game'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='time',
        ),
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
