# Generated by Django 4.2.7 on 2023-11-28 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0012_alter_country_options_remove_game_time_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
