# Generated by Django 4.2.7 on 2023-11-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0013_alter_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_fiveaway',
            field=models.CharField(default='LLLLL', max_length=5),
        ),
        migrations.AddField(
            model_name='game',
            name='last_fivehome',
            field=models.CharField(default='LLLLL', max_length=5),
        ),
        migrations.AlterField(
            model_name='headtohead',
            name='g1',
            field=models.CharField(default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='headtohead',
            name='g2',
            field=models.CharField(default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='headtohead',
            name='g3',
            field=models.CharField(default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='headtohead',
            name='g4',
            field=models.CharField(default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='headtohead',
            name='g5',
            field=models.CharField(default='W', max_length=1),
        ),
    ]
