# Generated by Django 4.2.7 on 2023-11-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0014_game_lastfive_away_game_lastfive_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.TimeField(),
        ),
    ]
