# Generated by Django 4.2.7 on 2023-12-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0014_game_last_fiveaway_game_last_fivehome_and_more'),
        ('soccergames', '0015_alter_game_date'),
    ]

    operations = [
    ]
