# Generated by Django 4.2.7 on 2023-12-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0016_merge_20231204_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='last_fiveaway',
        ),
        migrations.RemoveField(
            model_name='game',
            name='last_fivehome',
        ),
        migrations.AddField(
            model_name='game',
            name='notwon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='won',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
