# Generated by Django 4.2.7 on 2023-12-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0017_remove_game_last_fiveaway_remove_game_last_fivehome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='slug',
            field=models.SlugField(default='-'),
        ),
    ]
