# Generated by Django 4.2.7 on 2023-12-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0019_alter_league_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='overone',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='overthree',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='overtwo',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
