# Generated by Django 4.2.7 on 2023-12-04 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0021_remove_game_headhead_remove_headtohead_g1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='headhead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccergames.headtohead'),
        ),
    ]
