# Generated by Django 4.2.7 on 2023-12-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0022_game_headhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='headtohead',
            name='notimp',
            field=models.CharField(default='W', max_length=5),
        ),
    ]
