# Generated by Django 4.2.7 on 2023-12-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0023_headtohead_notimp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headtohead',
            name='notimp',
            field=models.CharField(default='', max_length=5),
        ),
    ]
