# Generated by Django 4.2.7 on 2023-12-04 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0026_remove_game_headhead_game_firstteam_game_secondteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='firstteam',
        ),
        migrations.RemoveField(
            model_name='game',
            name='secondteam',
        ),
    ]
