# Generated by Django 4.2.7 on 2023-12-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0027_remove_game_firstteam_remove_game_secondteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headtohead',
            name='notimp',
        ),
    ]
