# Generated by Django 4.2.7 on 2023-12-05 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0028_remove_headtohead_notimp'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='headhead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soccergames.headtohead'),
        ),
    ]
