# Generated by Django 4.2.7 on 2023-12-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0031_alter_gamedates_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedates',
            name='dates',
            field=models.DateField(auto_now_add=True),
        ),
    ]
